class TmTableColumn < ActiveRecord::Base
  unloadable
  attr_accessible :id, :column_number, :column_name, :column_name_jp, :column_type, :column_size, :column_null, :column_default, :column_p_key, :column_f_key, :note, :tm_table_id,:_destroy
  belongs_to :tm_table

  # http://www.trail4you.com/TechNote/Ruby/Rails_keyword_list.html
  RESERVED_WORDS = %w(@BASE_PATH ABS ABSOLUTE ACCEPT ACCESSIBLE ACTION
    ACTIONCONTROLLER ACTIONVIEW ACTIVERECORD ADD ADDITIONAL_LOAD_PATHS
    ADMIN AFTER AGGREGATE ALIAS ALL ALLOCATE ALTER ANALYSE ANALYZE AND
    ANY APPLICATION2 ARE ARGF ARGUMENTERROR ARGV ARRAY ARRAY_AGG AS ASC
    ASENSITIVE ASSERTION ASYMMETRIC AT ATOMIC ATTRIBUTES AUTHORIZATION
    AVG BASICSOCKET BEFORE BEGIN BENCHMARK BETWEEN BIGINT BIGNUM BINARY
    BINDING BIT BIT_LENGTH BLOB BOOLEAN BOTH BREADTH BY CALL CALLBACK
    CALLED CARDINALITY CASCADE CASCADED CASE CAST CATALOG CATEGORIE CEIL
    CEILING CGI CGIMETHODS CHANGE CHAR CHARACTER CHARACTER_LENGTH
    CHAR_LENGTH CHECK CLASS CLASSINHERITABLEATTRIBUTES CLOB CLOSE
    COALESCE COLLATE COLLATION COLLECT COLUMN COMMIT COMPARABLE
    COMPLETION CONCURRENTLY CONDITION CONDITIONVARIABLE CONFIG CONNECT
    CONNECTION CONSTRAINT CONSTRAINTS CONSTRUCTOR CONTAINS CONTINUATION
    CONTINUE CONVERT CORR CORRESPONDING COUNT COVAR_POP COVAR_SAMP
    CREATE CROSS CROSS_COMPILING CUBE CUME_DIST CURRENT CURRENT_CATALOG
    CURRENT_DATE CURRENT_DEFAULT_TRANSFORM_GROUP CURRENT_PATH
    CURRENT_ROLE CURRENT_SCHEMA CURRENT_TIME CURRENT_TIMESTAMP
    CURRENT_TRANSFORM_GROUP_FOR_TYPE CURRENT_USER CURSOR CYCLE DATA
    DATABASE DATABASES DATALINK DATE DATETIME DAY DAY_HOUR
    DAY_MICROSECOND DAY_MINUTE DAY_SECOND DEALLOCATE DEC DECIMAL DECLARE
    DEFAULT DEFERRABLE DEFERRED DELAYED DELEGATER DELEGATOR DELETE
    DENSE_RANK DEPTH DEREF DESC DESCRIBE DESCRIPTOR DESTROY DESTRUCTOR
    DETERMINISTIC DIAGNOSTICS DICTIONARY DIGEST DIR DISCONNECT
    DISPATCHER DISPLAY1 DISTINCT DISTINCTROW DIV DLNEWCOPY DLPREVIOUSCOPY
    DLURLCOMPLETE DLURLCOMPLETEONLY DLURLCOMPLETEWRITE DLURLPATH
    DLURLPATHONLY DLURLPATHWRITE DLURLSCHEME DLURLSERVER DLVALUE DO
    DOMAIN DOUBLE DRB DRBIDCONV DRBOBJECT DRBUNDUMPED DRIVE DROP DUAL
    DYNAMIC EACH ELEMENT ELSE ELSEIF ENCLOSED END END-EXEC ENUMERABLE
    ENV EOFERROR EQUALS ERB ERRNO ERRORS ESCAPE ESCAPED EVERY EXCEPT
    EXCEPTION EXEC EXECUTE EXISTS EXIT EXP EXPLAIN EXTERNAL EXTRACT
    FALSE FALSECLASS FCNTL FETCH FILE FILELIST FILETASK FILETEST
    FILEUTILS FILTER FIRST FIRST_VALUE FIXNUM FLOAT FLOAT4 FLOAT8
    FLOATDOMAINERROR FLOOR FOR FORCE FOREIGN FORMAT FOUND FREE FREEZE
    FROM FULL FULLTEXT FUNCTION FUSION GC GEM GENERAL GET GETOPTLONG
    GLOBAL GO GOTO GRANT GROUP GROUPING HANDLER HASH HAVING HIGH_PRIORITY
    HOLD HOST HOUR HOUR_MICROSECOND HOUR_MINUTE HOUR_SECOND IDENTITY IF
    IGNORE IGNORE_SERVER_IDS ILIKE IMMEDIATE IMPORT IN INDEX INDEXERROR
    INDICATOR INFILE INFLECTOR INITIALIZE INITIALLY INNER INOUT INPUT
    INSENSITIVE INSERT INT INT1 INT2 INT3 INT4 INT8 INTEGER INTERRUPT
    INTERSECT INTERSECTION INTERVAL INTO IO IOERROR IPSOCKET IS ISNULL
    ISOLATION ITERATE JOIN KERNEL KEY KEYS KILL LAG LANGUAGE LARGE LAST
    LAST_VALUE LATERAL LAYOUT LEAD LEADING LEAVE LEFT LESS LEVEL LIKE
    LIKE_REGEX LIMIT LINEAR LINES LINK LN LN_SUPPORTED LOAD LOADERROR
    LOCAL LOCALJUMPERROR LOCALTIME LOCALTIMESTAMP LOCATOR LOCK LOGGER
    LONG LONGBLOB LONGTEXT LOOP LOWER LOW_PRIORITY MAP MARSHAL
    MASTER_HEARTBEAT_PERIOD MASTER_SSL_VERIFY_SERVER_CERT MATCH MATCHDATA
    MATCHINGDATA MATH MAX MAXVALUE MAX_CARDINALITY MEDIUMBLOB MEDIUMINT
    MEDIUMTEXT MEMBER MERGE METHOD MIDDLEINT MIN MINUTE MINUTE_MICROSECOND
    MINUTE_SECOND MOD MODIFIES MODIFY MODULE MONTH MULTISET MUTEX MYSQL
    MYSQLERROR MYSQLFIELD MYSQLRES NAMEERROR NAMES NATIONAL NATURAL NCHAR NCLOB
    NEW NEW, NEXT NIL NILCLASS NO NOMEMORYERROR NOMETHODERROR NONE NORMALIZE
    NOT NOTIFY NOTIMPLEMENTEDERROR NOTNULL NOWRITE NO_WRITE_TO_BINLOG NTH_VALUE
    NTILE NULL NULLIF NUMERIC OBJECT OBJECTSPACE OBSERVABLE OBSERVER
    OCCURRENCES_REGEX OCTET_LENGTH OF OFF OFFSET OLD ON ONLY OPEN OPERATION
    OPTIMIZE OPTION OPTIONALLY OPT_TABLE OR ORDER ORDINALITY OUT OUTER OUTFILE
    OUTPUT OVER OVERLAPS OVERLAY PAD PARAMETER PARAMETERS PARSEDATE PARTIAL
    PARTITION PATH PERCENTILE_CONT PERCENTILE_DISC PERCENT_RANK PGCONN PGERROR
    PGLARGE PGRESULT PLACING PLATFORM POSITION POSITION_REGEX POSTFIX POWER
    PRECISION PREFIX PREORDER PREPARE PRESERVE PRIMARY PRIOR PRIVILEGES PROC
    PROCEDURE PROCESS PSTORE PUBLIC PURGE QUEUE QUOTE RACK RAKE RAKEAPP
    RAKEFILEUTILS RAKEVERSION RANGE RANGEERROR RANK RATIONAL READ READS
    READ_WRITE REAL RECORDS RECURSIVE REF REFERENCES REFERENCING REGEXP
    REGEXPERROR REGR_AVGX REGR_AVGY REGR_COUNT REGR_INTERCEPT REGR_R2
    REGR_SLOPE REGR_SXX REGR_SXY REGR_SYY RELATIVE RELEASE RELEASE_DATE RENAME
    RENDER REPEAT REPLACE REQUEST REQUIRE RESIGNAL RESPONSES RESTRICT RESULT
    RETURN RETURNING RETURNS REVOKE RIGHT RLIKE ROLE ROLLBACK ROLLUP ROUTINE
    ROW ROWS ROW_NUMBER RUBY RUBY_PLATFORM RUBY_RELEASE_DATE RUBY_VERSION
    RUNTIMEERROR SAVE SAVEPOINT SCANERROR SCHEMA SCHEMAS SCOPE SCRIPTERROR
    SCROLL SEARCH SECOND SECOND_MICROSECOND SECTION SECURITYERROR SELECT SEND
    SENSITIVE SEPARATOR SEQUENCE SESSION SESSION_USER SET SETS SHOW SIGNAL
    SIGNALEXCEPTION SIMILAR SIMPLEDELEGATER SIMPLEDELEGATOR SINGLETON SINGULAR
    SIZE SIZEDQUEUE SLOW SMALLINT SOCKET SOCKETERROR SOME SPACE SPATIAL
    SPECIFIC SPECIFICTYPE SQL SQLCODE SQLERROR SQLEXCEPTION SQLSTATE SQLWARNING
    SQL_BIG_RESULT SQL_CALC_FOUND_ROWS SQL_SMALL_RESULT SQRT SSL STANDARDERROR
    START STARTING STATE STATEMENT STATIC STDDEV_POP STDDEV_SAMP STDERR STDIN
    STDOUT STRAIGHT_JOIN STRING STRINGSCANNER STRUCT STRUCTURE SUBMULTISET
    SUBSTRING SUBSTRING_REGEX SUM SYMBOL SYMMETRIC SYNTAXERROR SYSTEM
    SYSTEMCALLERROR SYSTEMEXIT SYSTEMSTACKERROR SYSTEM_USER TABLE TABLESAMPLE
    TASK TCPSERVER TCPSOCKET TEMPLATE TEMPORARY TERM TERMINATE TERMINATED TEST
    TEXT THAN THEN THREAD THREADERROR THREADGROUP TIME TIMEOUT TIMESTAMP
    TIMEZONE_HOUR TIMEZONE_MINUTE TINYBLOB TINYINT TINYTEXT TO TOPLEVEL_BINDING
    TO_S TRAILING TRANSACTION TRANSLATE TRANSLATE_REGEX TRANSLATION TREAT
    TRIGGER TRIM TRIM_ARRAY TRUE TRUECLASS TRUNCATE TYPE TYPEERROR UDPSOCKET
    UESCAPE UNBOUNDMETHOD UNDER UNDO UNION UNIQUE UNIXSERVER UNIXSOCKET UNKNOWN
    UNLOCK UNNEST UNSIGNED UNTIL UPDATE UPPER URI URL USAGE USE USER USING
    UTC_DATE UTC_TIME UTC_TIMESTAMP VALID VALUE VALUES VARBINARY VARCHAR
    VARCHARACTER VARIABLE VARIADIC VARYING VAR_POP VAR_SAMP VERBOSE VERSION
    VIEW VISITS WHEN WHENEVER WHERE WHILE WIDTH_BUCKET WINDOW WITH WITHIN
    WITHOUT WORK WRITE XML XMLAGG XMLATTRIBUTES XMLBINARY XMLCAST XMLCOMMENT
    XMLCONCAT XMLDOCUMENT XMLELEMENT XMLEXISTS XMLFOREST XMLITERATE
    XMLNAMESPACES XMLPARSE XMLPI XMLQUERY XMLROOT XMLSERIALIZE XMLTABLE XMLTEXT
    XMLVALIDATE XOR YAML YEAR YEAR_MONTH ZERODIVISIONERROR ZEROFILL ZONE)

  COLUMN_TYPE = %w(binary boolean date datetime decimal float integer
    primary_key string text time timestamp)

  validates :column_name, :presence => true
  # 予約語チェック
  # validates :column_name, exclusion: { in: RESERVED_WORDS }
  validates_each  :column_name  do |record, attr, value|
    record.errors.add(attr, :exclusion) if RESERVED_WORDS.include?(value.upcase)
  end

  validates :column_name_jp, :presence => true
  validates :column_type, :presence => true
  validates :column_type, inclusion: { in: COLUMN_TYPE ,:allow_blank => true }
end
